version: "3.8"
services:
  backend:
    build: ./backend
    container_name: duniversity-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/duniversity
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: duniversity-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  mongo:
    image: mongo:6
    container_name: duniversity-mongo
    restart: always
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

volumes:
  mongo-data:
